spring:
  application:
    name: vol-service
  # --- Configuration de la base de données ---
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: travel_app_user
    password: MON_MOT_DE_PASSE_DB
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# --- Configuration du port (à la racine, PAS sous "spring") ---
server:
  port: 8081
# --- Configuration Eureka (à la racine aussi) ---
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/ # <-- Utilisez l'IP explicite