# application.yml pour VOL-SERVICE (ou HOTEL-SERVICE)
spring:
  application:
    name: vol-service # Nom nécessaire pour les logs

# --- Reste de la configuration locale ---
server:
  port: 8081 # Port doit rester ici pour démarrer l'application

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    # Ces lignes sont maintenant redondantes si elles sont dans bootstrap.yml
    register-with-eureka: true
    fetch-registry: true