# FICHIER : vol-service/src/main/resources/application.yml (minimaliste)

spring:
  application:
    name: hotel-service # Nom nécessaire pour les logs

server:
  port: 8082 # Port doit rester ici pour démarrer l'application

# TOUTES LES SECTIONS DATASOURCE, JPA, ET EUREKA DOIVENT ÊTRE SUPPRIMÉES ICI.
# (Elles sont maintenant gérées par bootstrap.yml et le dépôt Git)